#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
# focus window that your mouse hovers on (disabled due to right click bugs)
yabai -m config debug_output                 off
yabai -m config focus_follows_mouse          off
# move mouse to focused window
yabai -m config mouse_follows_focus          off
yabai -m config window_placement             second_child
# floating windows always stay on top
yabai -m config window_topmost               off
# enable borders
yabai -m config window_border                off
# no clue what this is
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
# don't automatically rebalance windows
yabai -m config auto_balance                 off
# swap windows if moved with mouse
yabai -m config mouse_action1                move
# resize windows if resized with mouse
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  2
yabai -m config bottom_padding               2
yabai -m config left_padding                 2
yabai -m config right_padding                2
yabai -m config window_gap                   1

# SIP Required
# prevent border from being under the active window
yabai -m config active_window_border_topmost off
yabai -m config window_shadow                off
yabai -m config window_opacity               off
yabai -m config window_border_width          1
#yabai -m config active_window_border_color   0xffff145e
yabai -m config active_window_border_color   0xffaaaaaa
yabai -m config normal_window_border_color   0xffaaaaaa
